/**
 * <ConfirmationSheet> — DESIGN.md §5.3 (critical path). The human-in-the-loop gate for
 * money-touching actions: amount prominent, summary table, security indicator, MPIN/biometric
 * confirm. On approve it shows the success tick (DESIGN.md §6.3) then resolves.
 */
import { AnimatePresence, motion } from "framer-motion";
import { useState } from "react";
import { CheckCircle, ShieldCheck } from "../../lib/icons";
import { SPRING } from "../../lib/motion";
import { SBIButton } from "../atoms/SBIButton";
import { BottomSheet } from "./BottomSheet";

export function ConfirmationSheet({
  open,
  onClose,
  title = "Review & Confirm",
  headline,
  rows,
  confirmLabel = "Confirm with MPIN",
  onConfirm,
  successLabel = "Done",
}: {
  open: boolean;
  onClose: () => void;
  title: string;
  headline: string;
  rows: { k: string; v: string }[];
  confirmLabel?: string;
  onConfirm: () => Promise<void> | void;
  successLabel?: string;
}) {
  const [phase, setPhase] = useState<"idle" | "confirming" | "done">("idle");

  async function handle() {
    // Haptic feedback for financial action (if supported)
    if (typeof navigator !== "undefined" && navigator.vibrate) {
      navigator.vibrate([15, 30, 15]);
    }

    setPhase("confirming");
    await onConfirm();
    
    // Haptic feedback for success
    if (typeof navigator !== "undefined" && navigator.vibrate) {
      navigator.vibrate([50, 100, 50]);
    }
    setPhase("done");
    
    setTimeout(() => {
      onClose();
      setPhase("idle");
    }, 1600);
  }

  return (
    <BottomSheet open={open} onClose={phase === "idle" ? onClose : () => {}} title={title} height="74%">
      <AnimatePresence mode="wait">
        {phase === "done" ? (
          <motion.div
            key="done"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1, transition: SPRING }}
            className="flex h-full flex-col items-center justify-center gap-3 py-10 text-center"
          >
            <motion.span
              initial={{ scale: 0 }}
              animate={{ scale: 1, transition: SPRING }}
              className="text-credit"
            >
              <CheckCircle size={72} weight="fill" />
            </motion.span>
            <span className="t-title-lg text-content-primary">{successLabel}</span>
            <span className="t-body text-content-secondary">Governed action written to your account.</span>
          </motion.div>
        ) : (
          <motion.div key="form" exit={{ opacity: 0 }} className="flex flex-col gap-6 pt-2">
            <div className="flex flex-col items-center justify-center text-center">
              <div className="text-[13px] font-semibold tracking-widest uppercase text-slate-400 mb-1">AI Recommendation</div>
              <div className="text-[40px] font-bold text-slate-900 tracking-tight leading-none mb-2">{headline}</div>
              <div className="text-[15px] font-medium text-ai bg-ai-surface px-3 py-1 rounded-full">{rows.find(r => r.k === "Action")?.v || "Investment"}</div>
            </div>

            <div className="rounded-2xl border border-slate-100 bg-slate-50 p-5">
               <h4 className="text-[12px] font-bold tracking-widest text-slate-400 uppercase mb-3">Recommended Because</h4>
               <ul className="space-y-2">
                 <li className="flex items-start gap-2.5 text-[14px] text-slate-600">
                    <CheckCircle size={16} weight="fill" className="text-emerald-500 mt-0.5 shrink-0" />
                    Salary credited to {rows.find(r => r.k === "From")?.v?.split(" ••• ")[0] || "Account"}
                 </li>
                 <li className="flex items-start gap-2.5 text-[14px] text-slate-600">
                    <CheckCircle size={16} weight="fill" className="text-emerald-500 mt-0.5 shrink-0" />
                    Idle balance detected
                 </li>
                 <li className="flex items-start gap-2.5 text-[14px] text-slate-600">
                    <CheckCircle size={16} weight="fill" className="text-emerald-500 mt-0.5 shrink-0" />
                    Retirement goal behind target
                 </li>
               </ul>
            </div>

            <p className="text-[13px] text-slate-500 text-center px-4 leading-relaxed">
              This recommendation was generated by AI and requires your approval to proceed.
            </p>

            <div className="flex items-center justify-center gap-2 text-slate-400 mb-2">
              <ShieldCheck size={18} weight="fill" />
              <span className="text-[12px] font-medium uppercase tracking-widest">Secured by MPIN</span>
            </div>

            <SBIButton full onClick={handle} disabled={phase === "confirming"} className="h-14 rounded-2xl text-[16px] font-semibold bg-brand">
              {phase === "confirming" ? "Authorising…" : "Approve with MPIN"}
            </SBIButton>
            <SBIButton variant="ghost" full onClick={onClose} className="text-[15px] font-medium text-slate-500 hover:text-slate-900">
              Cancel
            </SBIButton>
          </motion.div>
        )}
      </AnimatePresence>
    </BottomSheet>
  );
}
