/**
 * <NotificationRow> — DESIGN.md §5.2 / §8.4 Pattern 4. AI notifications get the ai-surface
 * treatment + "Generated by YONO AI" footer; everything else stays YONO-native.
 */
import { PhIcon } from "../../lib/icons";

export interface Notif {
  id: string;
  kind: "security" | "transaction" | "offer" | "ai";
  title: string;
  body: string;
  time: string;
  unread?: boolean;
}

const ICON: Record<Notif["kind"], { name: string; cls: string }> = {
  security: { name: "WarningCircle", cls: "text-debit" },
  transaction: { name: "CurrencyInr", cls: "text-brand" },
  offer: { name: "Gift", cls: "text-[var(--colour-amber-900)]" },
  ai: { name: "Sparkle", cls: "text-ai" },
};

export function NotificationRow({ n }: { n: Notif }) {
  const meta = ICON[n.kind];
  const isAi = n.kind === "ai";
  return (
    <div
      className={[
        "flex gap-3 px-4 py-3",
        isAi ? "bg-ai-surface" : n.unread ? "bg-brand-50" : "bg-bg-surface",
      ].join(" ")}
    >
      <span
        className={[
          "grid h-10 w-10 shrink-0 place-items-center rounded-full",
          isAi ? "bg-white" : "bg-white",
          meta.cls,
        ].join(" ")}
      >
        <PhIcon name={meta.name} size={20} weight={isAi ? "fill" : "regular"} />
      </span>
      <div className="min-w-0 flex-1">
        <div className="flex items-center justify-between gap-2">
          <span className="t-title-sm text-content-primary">{n.title}</span>
          <span className="t-label-sm text-content-tertiary shrink-0">{n.time}</span>
        </div>
        <p className="t-body-sm text-content-secondary line-clamp-2">{n.body}</p>
        {isAi && <span className="t-label-sm text-ai mt-1 inline-block">Generated by YONO AI</span>}
      </div>
      {n.unread && !isAi && <span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-brand" />}
    </div>
  );
}
