"""
GraphPort — the thin adapter interface that every spine node traverses through
(BUILD_PROMPT §3 / §4.4). The embedded NetworkX graph is the default implementation;
`neo4j_adapter.py` is a later one-file swap with zero changes to any caller.

All eligibility / traversal / reasoning-path logic goes through this port so the
intelligence layer never knows (or cares) which graph backend is live.
"""
from __future__ import annotations

from typing import Optional, Protocol

from .schema import (
    Account,
    ConsentArtifact,
    Customer,
    Goal,
    LifeEvent,
    Persona,
    Product,
)


class GraphPort(Protocol):
    # ── projections ──
    def get_customer(self, customer_id: str) -> Optional[Customer]: ...
    def get_persona(self, customer_id: str) -> Optional[Persona]: ...
    def get_accounts(self, customer_id: str) -> list[Account]: ...
    def get_goals(self, customer_id: str) -> list[Goal]: ...
    def get_holdings_count(self, customer_id: str) -> int: ...
    def get_consents(self, customer_id: str) -> list[ConsentArtifact]: ...

    # ── traversal used by reasoning paths ──
    def latest_life_event(self, customer_id: str) -> Optional[LifeEvent]: ...
    def underfunded_goal_products(
        self, customer_id: str, goal_type: str
    ) -> list[tuple[Goal, Product]]: ...
    def is_eligible(self, customer_id: str, product_id: str) -> bool: ...
    def get_product(self, product_id: str) -> Optional[Product]: ...

    # ── write-back ──
    def set_dormancy(self, customer_id: str, state: str) -> None: ...
    def add_holding(self, customer_id: str, product_id: str) -> None: ...

    # ── aggregate (barrier twin + funnel) ──
    def all_customer_ids(self) -> list[str]: ...
    def friction_aggregate(self) -> list[dict]: ...
    def dormancy_counts(self) -> dict[str, int]: ...
